/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEWS;

import br.com.DAO.LaboratoriosDAO;
import br.com.DTO.LaboratorioDTO;
import br.com.DTO.PecasManutencaoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class TelaLaboratorios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLaboratorios
     */
    public TelaLaboratorios() {
        initComponents();
        
       LaboratoriosDAO maquinasDAO = new LaboratoriosDAO();
    maquinasDAO.carregarTabela(tableLab); // onde tabelaMaquinas é o seu JTable
    
    
    try {
        // Tenta trazer a tela para frente ao abrir
        this.setSelected(true);
    } catch (java.beans.PropertyVetoException e) {
        JOptionPane.showMessageDialog(this, "Erro ao tentar destacar a tela: " + e.getMessage());
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLab = new javax.swing.JTable();
        txtIdLab = new javax.swing.JTextField();
        txtNomeLab = new javax.swing.JTextField();
        txtLocalizacaoLab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Laboratórios cadastrados");

        tableLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Localização"
            }
        ));
        jScrollPane1.setViewportView(tableLab);

        txtIdLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLabActionPerformed(evt);
            }
        });

        txtNomeLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeLabActionPerformed(evt);
            }
        });

        txtLocalizacaoLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalizacaoLabActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Localização:");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeEditar.png"))); // NOI18N
        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconePesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeLimpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeAdd.png"))); // NOI18N
        btnIncluir.setText("incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/IconeExcluir.png"))); // NOI18N
        btnExcluir1.setText("excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdLab, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnPesquisar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnLimpar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnIncluir))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnExcluir1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(3, 3, 3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLocalizacaoLab, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(txtNomeLab)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdLab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeLab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocalizacaoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocalizacaoLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizacaoLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacaoLabActionPerformed

    private void txtIdLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLabActionPerformed

    private void txtNomeLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeLabActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int id_lab = Integer.parseInt(txtIdLab.getText());
        
          String nome = txtNomeLab.getText();
          String loc = txtLocalizacaoLab.getText();

        // Criação do objeto PecasManutencaoDTO
        LaboratorioDTO objLabDTO = new LaboratorioDTO();
        objLabDTO.setIdLab(id_lab); // Atribuir ao campo correto
        objLabDTO.setNome(nome); // Atribuir ao campo correto
        objLabDTO.setLocalizacao(loc); // Atribuir ao campo correto
       
        // Instância do PecasManutencaoDAO e chamada ao método editar
        LaboratoriosDAO objLabDAO = new LaboratoriosDAO();
        objLabDAO.editar(objLabDTO); // Chama o método para editar no PecasManutencaoDA
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // Chamada do método Pesquisar

        // Obtém o ID do campo de texto
        int idLab = Integer.parseInt(txtIdLab.getText());

        // Cria uma instância do DAO
        LaboratoriosDAO LabDAO = new LaboratoriosDAO();
        // Chama o método pesquisar e obtém o resultado
        LaboratorioDTO LabDTO = LabDAO.pesquisarUsuario(idLab);

        if (LabDTO != null) {
            // Preenche os campos com os dados do cliente encontrado

            txtNomeLab.setText(LabDTO.getNome());
            txtLocalizacaoLab.setText(LabDTO.getLocalizacao());
        } else {
            // Mostra uma mensagem de erro se o cliente não for encontrado
            JOptionPane.showMessageDialog(null, "laboratorio não cadastrado!");

            // Método para apagar os campos
            LabDAO.limpar();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        //metodo botao limpar

       LaboratoriosDAO objLabDAO = new LaboratoriosDAO();
        objLabDAO.limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

        try {
            if (txtNomeLab.getText().isEmpty() || txtLocalizacaoLab.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos obrigatórios!");
                return;
            }

            // Obtém os dados dos campos
            // Conversão do ID da máquina para int
            int idLab;
          
            try {
                idLab = Integer.parseInt(txtIdLab.getText());
               
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Os campos devem estar preenchidos com um número inteiro!");
                return;
            }
            
                 String nome = txtNomeLab.getText();
             String loc = txtLocalizacaoLab.getText();
            
            // Criação do objeto UsuarioDTO
            LaboratorioDTO objLabDTO = new LaboratorioDTO();
            objLabDTO.setIdLab(idLab);
            objLabDTO.setNome(nome);
            objLabDTO.setLocalizacao(loc);
            
            // Instância do UsuarioDAO para inserir
            LaboratoriosDAO objLabDAO = new LaboratoriosDAO();
            objLabDAO.inserirUsuario(objLabDTO);

            // Limpa os campos após a inserção
            objLabDAO.limpar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir laboratório: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        // TODO add your handling code here:
        String idLab = txtIdLab.getText();

        if (idLab.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo ID não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            LaboratorioDTO objLabDTO = new LaboratorioDTO();
            objLabDTO.setIdLab(Integer.parseInt(idLab)); // Altere para setIdUsuario se necessário

            LaboratoriosDAO objLabDAO = new LaboratoriosDAO();
            objLabDAO.excluir(objLabDTO); // Chama o método de exclusão

        }

    }//GEN-LAST:event_btnExcluir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLab;
    public static javax.swing.JTextField txtIdLab;
    public static javax.swing.JTextField txtLocalizacaoLab;
    public static javax.swing.JTextField txtNomeLab;
    // End of variables declaration//GEN-END:variables
}
