/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEWS;

import br.com.DAO.ManutencoesDAO;
import br.com.DTO.ManutencoesDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class TelaMaquinasManutencoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaManutencoes
     */
    public TelaMaquinasManutencoes() {
        initComponents();
        
        //carregar tabela 
        ManutencoesDAO ManutencoesDAO = new ManutencoesDAO();
    ManutencoesDAO.carregarTabela(tableManutencoes); // onde tabelaMaquinas é o seu JTable
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableManutencoes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdManutencao = new javax.swing.JTextField();
        txtIdMaquina = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BoxStatus = new javax.swing.JComboBox<>();
        BoxTipo = new javax.swing.JComboBox<>();
        btnExcluir1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        txtResponsavel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Manutenções:");

        tableManutencoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID manutenção", "ID máquina", "Tipo", "Data", "Descrição", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableManutencoes);

        jLabel2.setText("Nova manutenção:");

        jLabel3.setText("ID manutenção:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("ID máquina:");

        jLabel6.setText("Data:");

        jLabel7.setText("Descrição:");

        jLabel8.setText("Status:");

        BoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agendada", "Concluida", "Cancelada" }));
        BoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxStatusActionPerformed(evt);
            }
        });

        BoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventiva", "Corretiva" }));
        BoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxTipoActionPerformed(evt);
            }
        });

        btnExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/IconeExcluir.png"))); // NOI18N
        btnExcluir1.setText("excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeEditar.png"))); // NOI18N
        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconePesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeLimpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeAdd.png"))); // NOI18N
        btnIncluir.setText("incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        txtResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsavelActionPerformed(evt);
            }
        });

        jLabel9.setText("Responsavel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(txtIdManutencao)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(BoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtResponsavel))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir1)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(BoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(BoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir1))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxTipoActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
// TODO add your handling code here:
        String idManutencao = txtIdManutencao.getText();

        if (idManutencao.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo ID não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            ManutencoesDTO objManutencoesDTO = new ManutencoesDTO();
            objManutencoesDTO.setIdManutencao(Integer.parseInt(idManutencao)); // Altere para setIdUsuario se necessário

            ManutencoesDAO objManutencoesDAO = new ManutencoesDAO();
            objManutencoesDAO.excluir(objManutencoesDTO); // Chama o método de exclusão

        }
            


        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

           // TODO add your handling code here:
// Botão editar (adaptado para a classe UsuarioDAO)

   
    int id_maquina = Integer.parseInt(txtIdMaquina.getText());
    String tipo = BoxTipo.getSelectedItem().toString();
        String data = txtData.getText();
        String descricao = txtDescricao.getText();
        String responsavel = txtResponsavel.getText();
        String status = BoxStatus.getSelectedItem().toString();


 ManutencoesDTO objManutencoesDTO = new ManutencoesDTO();
        
   
        objManutencoesDTO.setIdMaquina(id_maquina);
        objManutencoesDTO.setTipo(tipo);
        objManutencoesDTO.setData(data);
        objManutencoesDTO.setDescricao(descricao);
        objManutencoesDTO.setStatus(status);
        objManutencoesDTO.setResponsavel(responsavel);
      
// Instância do UsuarioDAO
ManutencoesDAO objManutencoesDAO = new ManutencoesDAO();
objManutencoesDAO.editar(objManutencoesDTO); // Chama o método para editar no UsuarioDAO
        
    
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void BoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxStatusActionPerformed

    private void txtResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsavelActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
          // Chamada do método Pesquisar

// Obtém o ID do campo de texto
int idManutencoes = Integer.parseInt(txtIdManutencao.getText());

// Cria uma instância do DAO
ManutencoesDAO ManutencoesDAO = new ManutencoesDAO();
// Chama o método pesquisar e obtém o resultado
ManutencoesDTO ManutencoesDTO = ManutencoesDAO.pesquisarUsuario(idManutencoes);

if (ManutencoesDTO != null) {
    // Preenche os campos com os dados do cliente encontrado
    txtIdMaquina.setText(String.valueOf(ManutencoesDTO.getIdMaquina()));
    BoxTipo.setSelectedItem(ManutencoesDTO.getTipo()); // Define o perfil na JComboBox
    BoxStatus.setSelectedItem(ManutencoesDTO.getStatus()); // Define o perfil na JComboBox
    txtResponsavel.setText(ManutencoesDTO.getResponsavel());
    txtData.setText(ManutencoesDTO.getData());
    txtDescricao.setText(ManutencoesDTO.getDescricao());
} else {
    // Mostra uma mensagem de erro se o cliente não for encontrado
    JOptionPane.showMessageDialog(null, "Manutenção não cadastrada!");

    // Método para apagar os campos
    ManutencoesDAO.limpar();
}


        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        
                                          
    try {
        if (txtIdManutencao.getText().isEmpty() 
                || txtIdMaquina.getText().isEmpty()
                || BoxTipo.getSelectedItem() == null
                || txtData.getText().isEmpty()
                || txtDescricao.getText().isEmpty()
                || txtResponsavel.getText().isEmpty()
                || BoxStatus.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos obrigatórios!");
            return;
        }

         // Conversão do ID da máquina para int
    int id_maquina;
    try {
        id_maquina = Integer.parseInt(txtIdMaquina.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "O campo ID Máquina deve ser um número inteiro!");
        return;
    }
        
        
        // Obtém os dados dos campos
        
        /*String id_maquina = txtIdMaquina.getText();
        String id_lab = txtIdLab.getText();*/
        
        String tipo = BoxTipo.getSelectedItem().toString();
        String data = txtData.getText();
        String descricao = txtDescricao.getText();
        String responsavel = txtResponsavel.getText();
        String status = BoxStatus.getSelectedItem().toString();

        
        
        
        // Criação do objeto UsuarioDTO
       ManutencoesDTO objManutencoesDTO = new ManutencoesDTO();
        
        /*objMaquin asDTO.setIdMaquina(id_maquina);
        objMaquinasDTO.setIdLab(id_lab);*/
        
        objManutencoesDTO.setIdMaquina(id_maquina);
        objManutencoesDTO.setTipo(tipo);
        objManutencoesDTO.setData(data);
        objManutencoesDTO.setDescricao(descricao);
        objManutencoesDTO.setStatus(status);
        objManutencoesDTO.setResponsavel(responsavel);
      
        // Instância do UsuarioDAO para inserir
        ManutencoesDAO objManutencoesDAO = new ManutencoesDAO();
        objManutencoesDAO.inserirUsuario(objManutencoesDTO);

        // Limpa os campos após a inserção
        objManutencoesDAO.limpar();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao incluir manutenção: " + e.getMessage());
    }

        
      

        


        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

          //metodo botao limpar
          
       ManutencoesDAO objManutencoesDAO = new ManutencoesDAO();       
            objManutencoesDAO.limpar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> BoxStatus;
    public static javax.swing.JComboBox<String> BoxTipo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableManutencoes;
    public static javax.swing.JTextField txtData;
    public static javax.swing.JTextField txtDescricao;
    public static javax.swing.JTextField txtIdManutencao;
    public static javax.swing.JTextField txtIdMaquina;
    public static javax.swing.JTextField txtResponsavel;
    // End of variables declaration//GEN-END:variables
}
